// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANytjwfO0UnHZePxbIxomE2yuPgygey9Y',
    appId: '1:361201097177:web:f72e4de76cd5ce025661c8',
    messagingSenderId: '361201097177',
    projectId: 'thunder-thursday',
    authDomain: 'thunder-thursday.firebaseapp.com',
    storageBucket: 'thunder-thursday.firebasestorage.app',
    measurementId: 'G-C6YHMXMBZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfnr3SRtuLKM4HbYuyV0-J5UL9ajZn-xs',
    appId: '1:361201097177:android:b904d236eeb2b1545661c8',
    messagingSenderId: '361201097177',
    projectId: 'thunder-thursday',
    storageBucket: 'thunder-thursday.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj-GH24nGJWmhwr-pFWFrbLc2QJOkFI4E',
    appId: '1:361201097177:ios:5cccc5d86a073c915661c8',
    messagingSenderId: '361201097177',
    projectId: 'thunder-thursday',
    storageBucket: 'thunder-thursday.firebasestorage.app',
    iosBundleId: 'com.example.thunderThursdayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj-GH24nGJWmhwr-pFWFrbLc2QJOkFI4E',
    appId: '1:361201097177:ios:5cccc5d86a073c915661c8',
    messagingSenderId: '361201097177',
    projectId: 'thunder-thursday',
    storageBucket: 'thunder-thursday.firebasestorage.app',
    iosBundleId: 'com.example.thunderThursdayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANytjwfO0UnHZePxbIxomE2yuPgygey9Y',
    appId: '1:361201097177:web:86faef88d4dcf8bb5661c8',
    messagingSenderId: '361201097177',
    projectId: 'thunder-thursday',
    authDomain: 'thunder-thursday.firebaseapp.com',
    storageBucket: 'thunder-thursday.firebasestorage.app',
    measurementId: 'G-MFSDX7C423',
  );
}
